### ISSUE TITLE
fix images problem when on heroku

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/bike-trader#22]

**Comment by simonbru** [comment]
That's worth checking out: https://addons.heroku.com/cloudinary
Here they show it is supposed to be simple to use it with CarrierWave: https://devcenter.heroku.com/articles/cloudinary#carrierwave-integration
But if you look at the detailed page it may not be that simple: http://cloudinary.com/documentation/rails_carrierwave

If we can make the imags work on heroku now I don't think it is worth it for tonight but it may still be interesting to try it in the projet.

**Comment by liechtia** [comment]
should be fixed i hope...
