### ISSUE TITLE
Only users and not owner should be able to bid

### ISSUE THREAD

**Issue by jocelynthode** [jocelynthode/bike-trader#26]
It's only implemented in the view at the moment, it should be bimplemented in the controller too using before_action.  The code require_permission from the auction controller should be usable.

I can work on that but if @jungomi or @liechtia wants to work on it it's fine too.

**Comment by liechtia** [comment]
i don't get what you mean, sorry...

**Comment by jocelynthode** [comment]
My bad my title was wrong I was meaning that we had to do a filter on the controller side in bids, I'm tired so my title didn't make any sense ./
