### ISSUE TITLE
Controller and model for Auction

### ISSUE THREAD

**Issue by jocelynthode** [jocelynthode/bike-trader#5]
Generate the controller and the model for the auction

**Comment by liechtia** [comment]
create_table :auctions do |t|
      t.string :title
      t.text :text
      t.datetime :start
      t.datetime :end
      t.timestamp :timeToEnd
      t.boolean :isFinished
      t.string :kwh
      t.string :mileage
      t.string :color
      t.string :brand
      t.references :user

**Comment by liechtia** [comment]
rename_column :auctions, :timeToEnd, :time_to_end
rename_column :auctions, :isFinished, :is_finished
